version: '2'
services:
  laravel.test:
    build:
      context: ./docker/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - target: 80
        published: ${FORWARD_APP_PORT:-8001}
        protocol: tcp
        mode: host
      - target: 5173
        published: ${VITE_PORT:-5174}
        protocol: tcp
        mode: host
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    networks:
      sail: {}
    depends_on:
      redis:
        condition: service_started
      meilisearch:
        condition: service_started
      mailpit:
        condition: service_started
      selenium:
        condition: service_started
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6380}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7701}:7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    volumes:
      - 'sail-meilisearch:/meili_data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://localhost:7700/health'
      retries: 3
      timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1026}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8026}:8025'
    networks:
      - sail
  selenium:
    image: selenium/standalone-chrome
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - sail
  mongo:
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DB_DATABASE}'
    volumes:
      - 'sailmongo:/data/db'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
  sailmongo:
    driver: local
